/**
 * payload-types.ts
 *
 * Manually generated Payload CMS types.
 * Based on collections: users, profiles, media, tags, tools, cases.
 *
 * Note: This file should be auto-generated by `payload generate:types`.
 * Manual generation was required due to tsx module resolution issues.
 *
 * Related:
 * - payload.config.ts
 * - payload/collections/
 */

export interface Config {
  collections: {
    users: User
    profiles: Profile
    media: Media
    tags: Tag
    tools: Tool
    cases: Case
    'payload-locked-documents': PayloadLockedDocument
    'payload-preferences': PayloadPreference
    'payload-migrations': PayloadMigration
  }
  globals: {}
  locale: 'nl' | 'en' | 'es'
  user: User
}

// === Users ===
export interface User {
  id: number
  email: string
  name?: string | null
  role?: 'admin' | 'editor' | null
  updatedAt: string
  createdAt: string
  enableAPIKey?: boolean | null
  apiKey?: string | null
  apiKeyIndex?: string | null
  loginAttempts?: number | null
  lockUntil?: string | null
  password?: string | null
}

// === Profiles ===
export interface Profile {
  id: number
  clerkUserId: string
  email?: string | null
  name?: string | null
  avatarUrl?: string | null
  bio?: string | null
  updatedAt: string
  createdAt: string
}

// === Media ===
export interface Media {
  id: number
  alt: string
  updatedAt: string
  createdAt: string
  url?: string | null
  thumbnailURL?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  focalX?: number | null
  focalY?: number | null
  sizes?: {
    thumbnail?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
    card?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
    featured?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
  }
}

// === Tags ===
export interface Tag {
  id: number
  slug: string
  name: string
  updatedAt: string
  createdAt: string
}

// === Tools ===
export interface Tool {
  id: number
  slug: string
  name: string
  websiteUrl?: string | null
  updatedAt: string
  createdAt: string
}

// === Cases ===
export interface Case {
  id: number
  slug: string
  status: 'draft' | 'published' | 'archived'
  visibility: 'public' | 'featured' | 'paid'
  source: 'editorial' | 'community'
  title: string
  oneLiner: string
  featuredImage?: number | Media | null
  tags?: (number | Tag)[] | null
  tools?: (number | Tool)[] | null
  problem?: string | null
  solution?: string | null
  stack?: string | null
  learnings?: string | null
  ownerProfileId?: string | null
  publishedAt?: string | null
  updatedAt: string
  createdAt: string
}

// === Payload Internal ===
export interface PayloadLockedDocument {
  id: number
  document?: {
    relationTo: 'users' | 'profiles' | 'media' | 'tags' | 'tools' | 'cases'
    value: number | User | Profile | Media | Tag | Tool | Case
  } | null
  globalSlug?: string | null
  user: { relationTo: 'users'; value: number | User }
  updatedAt: string
  createdAt: string
}

export interface PayloadPreference {
  id: number
  user: { relationTo: 'users'; value: number | User }
  key?: string | null
  value?: unknown
  updatedAt: string
  createdAt: string
}

export interface PayloadMigration {
  id: number
  name?: string | null
  batch?: number | null
  updatedAt: string
  createdAt: string
}

// === Type Guards ===
export function isMedia(doc: number | Media): doc is Media {
  return typeof doc === 'object' && doc !== null && 'url' in doc
}

export function isTag(doc: number | Tag): doc is Tag {
  return typeof doc === 'object' && doc !== null && 'slug' in doc && 'name' in doc
}

export function isTool(doc: number | Tool): doc is Tool {
  return typeof doc === 'object' && doc !== null && 'slug' in doc && 'name' in doc
}
